"""Subject → skill tree, and what each tree is worth. GENERATED — do not edit.

Written by scripts/gen_tree_map.mjs from frontend/src/skills/subjectMap.ts and
frontend/src/skills/subjectTrees.ts, which are the authority. `npm run
check:trees` fails if this file is not what those two would produce, so editing
it here is a change that gets reverted by the next build rather than a change.

See the module note in scripts/gen_tree_map.mjs for why the copy exists at all:
badges are counted on the server from the account's own rows, and the server
cannot ask the browser which lattice a task was on.
"""

#: Catalogue subject id → the tree it opens. Every id in
#: backend/config/subjects.py appears here; scripts/check_trees.mjs is what
#: keeps that true.
SUBJECT_TREE = {
    'mathematics': 'mathematics',
    'algebra': 'mathematics',
    'calculus': 'calculus',
    'geometry': 'mathematics',
    'statistics': 'statistics',
    'physics': 'physics',
    'chemistry': 'chemistry',
    'biology': 'biology',
    'anatomy': 'biology',
    'genetics': 'biology',
    'astronomy': 'earth-space',
    'geology': 'earth-space',
    'ecology': 'biology',
    'science': 'science',
    'homework': 'study',
    'revision': 'study',
    'exams': 'study',
    'lectures': 'study',
    'research': 'study',
    'thesis': 'writing',
    'coursework': 'study',
    'tutoring': 'study',
    'study_group': 'study',
    'flashcards': 'study',
    'english': 'language',
    'literature': 'literature',
    'writing': 'writing',
    'grammar': 'language',
    'vocabulary': 'language',
    'spanish': 'foreign-language',
    'french': 'foreign-language',
    'german': 'foreign-language',
    'japanese': 'foreign-language',
    'mandarin': 'foreign-language',
    'history': 'history',
    'geography': 'humanities',
    'philosophy': 'philosophy',
    'psychology': 'psychology',
    'sociology': 'humanities',
    'politics': 'humanities',
    'programming': 'coding',
    'computer_science': 'algorithms',
    'web_design': 'web',
    'data_science': 'data-science',
    'machine_learning': 'machine-learning',
    'cybersecurity': 'cybersecurity',
    'databases': 'databases',
    'networking': 'networking',
    'robotics': 'robotics',
    'engineering': 'physics',
    'economics': 'economics',
    'business': 'business',
    'marketing': 'marketing',
    'accounting': 'business',
    'finance': 'finance',
    'budgeting': 'business',
    'investing': 'finance',
    'taxes': 'business',
    'law': 'business',
    'management': 'management',
    'work': 'career',
    'meetings': 'career',
    'email': 'career',
    'calls': 'career',
    'admin': 'life',
    'planning': 'productivity',
    'presenting': 'career',
    'reports': 'writing',
    'interviews': 'career',
    'job_search': 'career',
    'art': 'art',
    'drawing': 'drawing',
    'design': 'design',
    'photography': 'photography',
    'music': 'music',
    'guitar': 'guitar',
    'piano': 'piano',
    'singing': 'voice',
    'dance': 'fitness',
    'film': 'film',
    'gym': 'strength',
    'running': 'endurance',
    'cycling': 'endurance',
    'swimming': 'endurance',
    'yoga': 'mindfulness',
    'meditation': 'mindfulness',
    'nutrition': 'nutrition',
    'sleep': 'mindfulness',
    'therapy': 'mindfulness',
    'health': 'fitness',
    'chores': 'life',
    'laundry': 'life',
    'cooking': 'cooking',
    'groceries': 'life',
    'errands': 'life',
    'family': 'life',
    'friends': 'life',
    'travel': 'travel',
    'reading': 'language',
    'journaling': 'mindfulness',
}

#: Tree id → (title, total XP of its holdable nodes).
#:
#: The total skips navigation nodes: a doorway into a child tree is not a skill
#: somebody holds, and counting its worth would charge them twice for the tree
#: behind it.
TREES = {
    'coding': ('Coding', 43750),
    'web': ('Web Development', 38300),
    'algorithms': ('Algorithms & Data Structures', 40300),
    'graphs': ('Graph Algorithms', 26600),
    'systems': ('Systems', 36000),
    'networking': ('Networking', 37200),
    'data-science': ('Data Science', 37800),
    'machine-learning': ('Machine Learning', 44700),
    'databases': ('Databases', 38300),
    'cybersecurity': ('Cybersecurity', 41700),
    'competitive-programming': ('Competitive Programming', 42100),
    'robotics': ('Competitive Robotics', 34100),
    'mathematics': ('Mathematics', 34900),
    'calculus': ('Calculus', 33900),
    'statistics': ('Statistics & Probability', 40100),
    'linear-algebra': ('Linear Algebra', 40300),
    'discrete': ('Discrete Mathematics', 38300),
    'competition-math': ('Competition Mathematics', 43000),
    'science': ('Science', 30300),
    'physics': ('Physics', 42200),
    'chemistry': ('Chemistry', 39500),
    'biology': ('Biology', 41500),
    'earth-space': ('Earth & Space', 40000),
    'olympiad-science': ('Science Olympiad', 41200),
    'language': ('Language & Writing', 29700),
    'writing': ('Writing', 39200),
    'literature': ('Literature', 38200),
    'foreign-language': ('Foreign Languages', 38500),
    'humanities': ('Humanities', 32900),
    'history': ('History', 38100),
    'philosophy': ('Philosophy', 39000),
    'psychology': ('Psychology', 39200),
    'debate': ('Competitive Debate', 34600),
    'business': ('Business & Money', 32400),
    'finance': ('Personal Finance & Investing', 37500),
    'economics': ('Economics', 41400),
    'marketing': ('Marketing', 38700),
    'management': ('Management', 39400),
    'productivity': ('Productivity', 33100),
    'focus': ('Focus & Deep Work', 36000),
    'study': ('Studying', 37500),
    'career': ('Work & Career', 37300),
    'art': ('Art & Design', 30500),
    'drawing': ('Drawing & Painting', 38800),
    'design': ('Design', 37900),
    'photography': ('Photography', 37100),
    'film': ('Film & Video', 39400),
    'music': ('Music', 34600),
    'guitar': ('Guitar', 38500),
    'piano': ('Piano', 37900),
    'voice': ('Singing', 37500),
    'production': ('Music Production', 38500),
    'performance': ('Performance & Auditions', 36000),
    'fitness': ('Health & Fitness', 26300),
    'strength': ('Strength Training', 37300),
    'endurance': ('Endurance', 38400),
    'nutrition': ('Nutrition', 35900),
    'mindfulness': ('Mind & Recovery', 35300),
    'life': ('Life & Home', 27500),
    'cooking': ('Cooking', 34600),
    'travel': ('Travel', 34700),
}


def tree_for(subject):
    """The tree a subject opens, or None for one nothing routes.

    Unlike the client's `treeForSubject`, this does not fall back to the
    subject's group. A fallback is the right answer for a rail that has to put
    every subject *somewhere*; it is the wrong answer for a badge, where it
    would hand somebody credit in a lattice they have never opened because the
    subject they invented happened to land in Computing.
    """
    return SUBJECT_TREE.get(subject)
